apiVersion: apps/v1
kind: Deployment
metadata:
  name: mdb-api
  labels:
    app: mdb-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mdb-api
  template:
    metadata:
      labels:
        app: mdb-api
    spec:
      containers:
      - name: mdb-api
        image: dist-syst-mdb-api:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8002
        envFrom:
        - configMapRef:
            name: mdb-api-config
        env:
        - name: MDB_DATA_API_KEY
          valueFrom:
            secretKeyRef:
              name: mdb-api-secret
              key: MDB_DATA_API_KEY
        readinessProbe:
          httpGet:
            path: /health
            port: 8002
          initialDelaySeconds: 5
          periodSeconds: 15
